// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndfqibgreeydcjgcriel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZnFpYmdyZWV5ZGNqZ2NyaWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTAzNjcsImV4cCI6MjA2NzA4NjM2N30.Lng5RLPreTe8zTM0rho-uIDRDuE-5Kaqre9aQwkUOZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});